trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    python --version
    pip install -r requirements.txt
  displayName: 'Install dependencies'
- task: CmdLine@2
  inputs:
    script: |
      python addtwo.py
      pathonaddto